import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Noto_Sans_TC } from "next/font/google";

import HeaderBar from "@/components/home/HeaderBar";

import "@/app/styles/global.scss";

const inter = Inter({ subsets: ["latin"] });
const notoSansTC = Noto_Sans_TC({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " " + notoSansTC.className}>
        <HeaderBar />
        {children}
      </body>
    </html>
  );
}
